OBJS = seqig.o
SRC=../src
CXXFLAGS+=-I../../../core/include
CXXFLAGS+=-I../../../extras/include
CXXFLAGS+=-I../include

default: all
all: main

main: $(OBJS)
	$(CXX) $(LDFLAGS) $(OBJS) -o SeqIg

seqig.o: $(SRC)/SeqIg.h $(SRC)/SeqIg.cpp
	$(CXX) $(CXXFLAGS) -c $(SRC)/SeqIg.cpp 

clean:
	rm -f seqig.o

.PHONY: default all clean
